version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - discovery.zen.minimum_master_nodes=1
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    networks:
      elk:
        aliases:
          - elasticsearch
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.0.1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    restart: always
    ports:
      - 5601:5601
    networks:
      - elk
networks:
  elk: